project/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from fantasydrag.api.urls import urlpatterns as api_urls
from stats.api.urls import urlpatterns as stat_api_urls
from fantasydrag.urls import urlpatterns as app_urls
from legal.views import PolicyLanding, PrivacyPolicy, EULA

urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
    path(
        'privacy-policy/',
        PrivacyPolicy.as_view(),
        name='privacy_policy'
    ),
    path(
        'end-user-license-agreement/',
        EULA.as_view(),
        name='eula'
    ),
    path(
        'end-user-license-agreement/',
        TemplateView.as_view(template_name='pages/legal/v1/eula.html'),
        name='eula'
    ),
    path(
        'policy-update/',
        PolicyLanding.as_view(),
        name='policy_update'
    ),
] + app_urls + api_urls + stat_api_urls

stats/models.py
from django.db import models
from django.db.models import Sum

from fantasydrag.models import (
    Draft,
    DragRace,
    Episode,
    EpisodeDraft,
    Panel,
    Participant,
    Queen,
    Score,
    WildCardQueen,
    WildCardAppearance,
    ScoreClass
)


class StatModelBase(models.Model):
    class Meta:
        abstract = True

    @classmethod
    def get_or_create(cls, **kwargs):
        existing = cls.objects.filter(**kwargs)
        if existing.exists():
            instance = existing.first()
        else:
            instance = cls(**kwargs)
            instance.save()
        return instance

    @classmethod
    def destroy(cls, **kwargs):
        cls.objects.filter(**kwargs).delete()

    @classmethod
    def create(cls, **kwargs):
        instance = cls(**kwargs)
        instance.save()
        return instance


class ParticipantEpisodeDraftScoreBase(StatModelBase):
    class Meta:
        abstract = True
    total_score = models.IntegerField(default=0, db_index=True)
    rank_tier = models.IntegerField(default=0)
    total_participants = models.IntegerField(default=0)

    @classmethod
    def reset_or_create(cls, **kwargs):
        existing = cls.objects.filter(**kwargs)
        if existing.exists():
            instance = existing.first()
            instance.total_score = 0
            instance.rank_tier = 0
            instance.total_participants = 0
            instance.save()
        else:
            instance = cls(**kwargs)
            instance.save()
        return instance


class EpisodeDraftScore(ParticipantEpisodeDraftScoreBase):
    episodedraft = models.ForeignKey(EpisodeDraft, on_delete=models.CASCADE)
    participant = models.ForeignKey(
        Participant,
        on_delete=models.CASCADE,
        related_name='episode_draftscore_target_participant'

    )

    @property
    def episode(self):
        return self.episodedraft.episode

    @property
    def drag_race(self):
        return self.episodedraft.drag_race

    @property
    def drafted_queens(self):
        return self.episodedraft.queens

    def set_total_score(self):
        episode_sum = Score.objects.filter(
            episode=self.episode,
            queen__in=self.drafted_queens.all()
        ).aggregate(Sum('default_rule__point_value'))
        if episode_sum['default_rule__point_value__sum'] is not None:
            self.total_score = episode_sum['default_rule__point_value__sum']
        else:
            self.total_score = 0
        self.save()


class DragRaceDraftScore(ParticipantEpisodeDraftScoreBase):
    drag_race = models.ForeignKey(DragRace, on_delete=models.CASCADE)
    participant = models.ForeignKey(
        Participant,
        on_delete=models.CASCADE,
        related_name='dragrace_draftscore_target_participant'

    )

    @property
    def participant_draft_qs(self):
        return EpisodeDraft.objects.filter(
            episode__in=self.drag_race.episode,
            participant=self.viewing_participant
        )

    @property
    def all_draft_qs(self):
        return EpisodeDraft.objects.filter(
            episode__in=self.drag_race.episode
        )

    def set_total_score(self):
        draft_sum = self.participant_draft_qs.aggregate(Sum('total_score'))
        if draft_sum['total_score__sum'] is not None:
            self.total_score = draft_sum['total_score__sum']
        else:
            self.total_score = 0
        self.save()


class QueenEpisodeScoreBase(StatModelBase):
    class Meta:
        abstract = True

    queen = models.ForeignKey(Queen, on_delete=models.CASCADE)
    total_score = models.IntegerField(default=0, db_index=True)
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE)
    drag_race = models.ForeignKey(DragRace, on_delete=models.CASCADE)

    @property
    def episode_scores(self):
        return Score.objects.filter(episode=self.episode, queen=self.queen)

    def set_total_score(self):
        episode_sum = Score.objects.filter(
            episode=self.episode, queen=self.queen
        ).aggregate(Sum('default_rule__point_value'))
        if episode_sum['default_rule__point_value__sum'] is not None:
            self.total_score = episode_sum['default_rule__point_value__sum']
            self.save()
        else:
            self.delete()


class CanonicalQueenEpisodeScore(QueenEpisodeScoreBase):
    pass


class QueenEpisodeScore(QueenEpisodeScoreBase):
    viewing_participant = models.ForeignKey(
        Participant, on_delete=models.CASCADE, related_name='viewingparticipant_queen_episode_score')


class QueenDragRaceScoreBase(StatModelBase):
    class Meta:
        abstract = True
    queen = models.ForeignKey(Queen, on_delete=models.CASCADE)
    total_score = models.IntegerField(default=0, db_index=True)
    drag_race = models.ForeignKey(DragRace, on_delete=models.CASCADE)
    main_wins = models.IntegerField(default=0)
    mini_wins = models.IntegerField(default=0)
    lipsync_wins = models.IntegerField(default=0)
    safe_count = models.IntegerField(default=0)
    eliminated_count = models.IntegerField(default=0)
    bottom_count = models.IntegerField(default=0)

    @property
    def score_qs(self):
        return None

    @property
    def score_class_map(self):
        return {
            ScoreClass.objects.get(name='main_win'): 'main_wins',
            ScoreClass.objects.get(name='mini_win'): 'mini_wins',
            ScoreClass.objects.get(name='lipsync_win'): 'lipsync_wins',
            ScoreClass.objects.get(name='safe'): 'safe_count',
            ScoreClass.objects.get(name='elimination'): 'eliminated_count',
            ScoreClass.objects.get(name='bottom'): 'bottom_count',
            ScoreClass.objects.get(name='stay'): 'bottom_count',
        }

    @property
    def scores(self):
        return self.score_qs.all()

    @property
    def episodes(self):
        return self.viewing_participant.episodes.filter(drag_race=self.drag_race).all()

    @property
    def queen_scores(self):
        return Score.objects.filter(
            episode__in=self.episodes,
            queen=self.queen
        ).all()

    def set_total_score(self):
        episode_sum = self.score_qs.aggregate(Sum('total_score'))
        if episode_sum['total_score__sum']:
            self.total_score = episode_sum['total_score__sum']
        else:
            self.total_score = 0
        self.save()
        self.set_total_stats()

    def set_total_stats(self):
        self.main_wins = 0
        self.mini_wins = 0
        self.lipsync_wins = 0
        self.safe_count = 0
        self.eliminated_count = 0
        self.bottom_count = 0

        score_class_map = self.score_class_map
        for score in self.queen_scores:
            for score_class in score.rule.score_classes.all():
                if score_class in score_class_map:
                    current_count = getattr(self, score_class_map[score_class])
                    setattr(self, score_class_map[score_class], current_count + 1)
        self.save()


class CanonicalQueenDragRaceScore(QueenDragRaceScoreBase):

    @property
    def score_qs(self):
        return CanonicalQueenEpisodeScore.objects.filter(
            episode__drag_race=self.drag_race, queen=self.queen
        )

    @property
    def queen_scores(self):
        return Score.objects.filter(
            episode__drag_race=self.drag_race,
            queen=self.queen
        ).all()


class QueenDragRaceScore(QueenDragRaceScoreBase):
    viewing_participant = models.ForeignKey(
        Participant, on_delete=models.CASCADE, related_name='viewingparticipant_queen_dragrace_score')

    @property
    def score_qs(self):
        return QueenEpisodeScore.objects.filter(
            episode__drag_race=self.drag_race, queen=self.queen, viewing_participant=self.viewing_participant
        )


class PanelistEpisodeScore(StatModelBase):
    viewing_participant = models.ForeignKey(
        Participant, on_delete=models.CASCADE, related_name='viewingparticipant_panelist_episode_score')
    panel = models.ForeignKey(Panel, on_delete=models.CASCADE)
    panelist = models.ForeignKey(
        Participant, on_delete=models.CASCADE, related_name='targetparticipant_panelist_episode_score')
    total_score = models.FloatField(
        default=0,
        db_index=True
    )
    episode = models.ForeignKey(Episode, on_delete=models.CASCADE)

    @property
    def drafted_queens(self):
        drafts = Draft.objects.filter(
            participant=self.panelist,
            panel=self.panel
        )
        return [d.queen for d in drafts.all()]

    @property
    def wildcard_queens(self):
        wildcard_drafts = WildCardQueen.objects.filter(
            participant=self.panelist,
            panel=self.panel
        )
        return [d.queen for d in wildcard_drafts.all()]

    @property
    def scores(self):
        return QueenEpisodeScore.objects.filter(
            episode=self.episode,
            queen__in=self.drafted_queens,
            viewing_participant=self.viewing_participant
        ).all()

    @property
    def wildcard_scores(self):
        return WildCardAppearance.objects.filter(
            episode=self.episode,
            queen__in=self.wildcard_queens
        ).all()

    def set_total_score(self):
        episode_sum = QueenEpisodeScore.objects.filter(
            episode=self.episode,
            queen__in=self.drafted_queens,
            viewing_participant=self.viewing_participant
        ).aggregate(Sum('total_score'))

        wildcard_sum = 0
        for wqa in self.wildcard_scores:
            wildcard_sum += wqa.appearance.point_value

        if episode_sum['total_score__sum']:
            self.total_score = float(episode_sum['total_score__sum'])
        else:
            self.total_score = 0
        self.total_score += float(wildcard_sum)
        self.save()


class PanelistDragRaceScore(StatModelBase):
    viewing_participant = models.ForeignKey(

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} | About{% endblock %}

{% block page_content %}
<div class="row">
	<div class="col">
		<h1 class="marker">Welcome to Drag Crush!</h1>
		<div class="row">
			<div class="col">
				<p>Always wanted to be a part of RuPaul's Drag Race, 
				but lack the charisma, uniqueness, nerve and talent to get there? Well, now's your chance! Join Drag Crush to play along with current seasons, fantasy league style!
				</p>
			</div>
			{% if not request.user.is_authenticated %}
				<div class="col">
					{% if error %}
					<div class="alert alert-danger">{{error}}</div>
					{% endif %}
					<form method="POST" action="">
						{% csrf_token %}
						{{form.as_p}}
						<input type="submit" class="form-control btn btn-primary" value="Log In" />
					</form>
					Not registered? <a href="{% url 'register' %}">Go here</a>.
				</div>
			{% endif %}
		</div>
		<div class="row">
			<div class="col">
				<h3>Drag Crush is Better Than Other Drag Race Fantasy Leagues</h3>
				<ol>
					<li>
						<strong>It's spoiler proof!</strong> You don't see any scores or statistics for episodes that you have not indicated that you've seen. This includes your own scores and scores for other participants, as well as contestant scores.
					</li>
					<li>
						<strong>It's self-serve!</strong> You can start, manage, and join panels all on your own. No data entry is required on your part other than drafting your Drag Crush queens.
					</li>
					<li>
						<strong>It's more creative!</strong> The rules are more fun, and are tailored to the different types of Drag Races.
					</li>
					<li>
						<strong>It's flexible!</strong> With multiple ways to play, there's something for everyone - whether you are deeply competitive and want to compete directly against other Drag Race fans, fantasy league-style, or you just enjoy playing along with the season using the weekly draft. Or both!
					</li>
				</ol>
			</div>
		</div>
		<div class="row">
			<div class="col">
			<h3>Two Ways to Play</h3>
			<ol>
				<li><strong>On your own</strong> - Draft a fantasy team of queens from each upcoming episode of an onging Drag Race and accumulate points for your drafted queens. You can track how your team ranks against all other participants.</li>
				<li><strong>On a panel</strong> - Create a private panel of up to 20 participants with friends or join a public panel. Hop online at your panel's scheduled draft time to draft your fantasy Drag Race team. Panels have the additional option of drafting Wildqueens - queens from the master list of all RPDR contestants who might show up in a season and score you additional points.</li>
			</ol>

			<h3>Worried about spoilers?</h3>
			<p>Don't be! You won't see any scores until you choose to Ruveal them yourself.

			<h3>How does scoring work?</h3>
			<p>Your esteemed admin user, kittygirl, watches each episode and sets the scores based on predetermined rules. For older seasons, kittygirl is getting there and sometimes using wikipedia, with the goal of scoring all RPDR contestants for <i>statistics</i>. Why? Everyone loves statistics!</p>
			<p>Rules vary by what type of Drag Race it is:</p>
			<ol>
				<li><a href="{% url 'dragrace_rules' drag_race_type='standard' %}">Standard Drag Race</a></li>
				<li><a href="{% url 'dragrace_rules' drag_race_type='all star' %}">Drag Race All Stars</a></li>
				<li><a href="{% url 'dragrace_rules' drag_race_type='international' %}">International Drag Race</a></li>
			</ol>

			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/pages/contact.html
{% extends 'base.html' %}
{% load static helper_tags %}

{% block page_title %} | Contact{% endblock %}


{% block extra_scripts %}
	<script type="text/javascript" src="{% static 'angular/contact.js' %}"></script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.2/summernote.js"></script>

	<script type="text/javascript">

	</script>
{% endblock %}

{% block page_content %}
<div class="row">
	<div class="col">
		<h1>Contact</h1>
	</div>
</div>

<form method="POST" action="" id="contactMessage">
	{% csrf_token %}
	{% for field in form %}
	{% if field.name == 'content' %}
	<div class="row">
		<div class="col-2"></div>
		<div class="col">
			<span class="form-helptext" ng-show="messageType=='dispute'">
				Let Kittygirl know that you might have found an error in a score. Be as specific as possible by providing the Drag Race season, episode, and score that you think is incorrect or missing.
			</span>
			<span class="form-helptext" ng-show="messageType=='support'">
				Let Kittygirl know if you found a bug or error on the Drag Crush site. Be as specific as possible by providing relevant URLs and steps to reproduce the error.
			</span>
			<span class="form-helptext" ng-show="messageType=='general'">
				Let Kittygirl know any general feedback you have!
			</span>
		</div>
	</div>
	{% endif %}
	{% if field.name == 'dispute_type' %}
		<div class="row" ng-show="messageType=='dispute'">
	{% else %}
		<div class="row">
	{% endif %}
		<div class="col-2">
			<span class="form form-label form-label-small">
				{{ field.label_tag }} 
			</span>			
		</div>
		<div class="col">
			{{field.as_widget}}
			{% if field.name == 'message_type' %}
				<div class="form-error" ng-show="errors.message_type">Message type is required</div>
			{% elif field.name == 'dispute_type' %}
				<div class="form-error" ng-show="errors.dispute_type">Dispute type is required for message type 'disput a score'</div>
			{% elif field.name == 'content' %}
				<div class="form-error" ng-show="errors.content">Message content is required</div>
			{% endif %}
		</div>
	</div>
	{% endfor %}
	<div class="row">
		<div class="col">
			<input type="submit" class="form-control btn btn-primary" value="Submit" />
		</div>
	</div>
</form>


{% endblock %}

templates/pages/create-episode.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %} | New Episode{% endblock %}

{% block page_content %}
{% if error %}
<div class="row">
	<div class="col">
		<div class="alert alert-danger">{{error}}</div>
	</div>
</div>
{% endif %}
<div class="row">
	<div class="col">
		<form method="POST" action="">
			{% csrf_token %}
			<table class="table">
				{{form.as_table}}
				<tr>
					<td colspan="100%">
						<input type="submit" value="Submit" class="form-control btn btn-primary"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>

{% endblock %}

templates/pages/episodedetail.html
{% extends 'base.html' %}

{% block page_title %} | {{episode.title}} | {{episode.drag_race.display_name}}{% endblock %}

{% block page_content %}
{% if is_site_admin %}
<div class="row">
	<div class="col">
		<a href="{% url 'set_episode_scores' episode_id=episode.pk %}" class="form-control btn btn-primary">Score Episode</a>
	</div>
</div>
<div class="spacer-medium"></div>
{% endif %}

<div class="row">
	<div class="col">
		<h2><a href="{% url 'dragrace_stats' dragrace_id=drag_race.pk %}">{{episode.drag_race.display_name}}</a></h2>
	</div>
</div>
<div class="spacer-small"></div>
<div class="row">
	<div class="col">
		<h1 class="marker">Episode #{{episode.number}}: {{episode.title}}</h1>
	</div>
</div>
<div class="spacer-small"></div>
{% if episode.is_scored %}

<div class="row">
	<div class="col">
		<form method="POST" action="">
			{% csrf_token %}
			{% if episode_is_visible%}
				<input type="submit" id="id_hide" name="hide" value="Hide these scores" class="form-control btn btn-danger"/>
			{% else %}
				<input type="submit" id="id_ruveal" name="ruveal" value="RuVeal the scores!" class="form-control btn btn-success"/>
			{% endif %}
		</form>
	</div>
</div>
<div class="row">
	<div class="col">
		<table class="table">
			<tr>
				<th>Queen</th><th>Score</th><th>Points</th>
			</tr>
			{% if episode_is_visible %}
				{% for score in scores %}
					<tr>
						<th>{{score.queen.name}}</th>
						<td>
							<p>{{score.rule.name}}</p>
							<p class="text-secondary">{{score.rule.description}}</p>
						</td>
						<td>{{score.rule.point_value}}</td>
					</tr>
				{% endfor %}
			{% endif %}
		</table>
	</div>
</div>
{% else %}
<div class="row">
	<div class="col alert alert-warning">
		This episode isn't scored yet, come back later!
	</div>
</div>
{% endif %}
{% endblock %}

templates/pages/episodewildcards.html
{% extends 'base.html' %}
{% load static helper_tags %}

{% block extra_scripts %}
	<script type="text/javascript" src="{% static 'angular/episodewildcards.js' %}"></script>
{% endblock %}

{% block page_content %}
<span id='episodeWildQueensModule' ng-controller='episodeWildQueensController'>
	<input type="hidden" id="id_episodeId" value="{{episode.pk}}" />

	<div class="row">
		<div class="col">
			<a class="marker" href="{% url 'set_episode_scores' dragrace_id=drag_race.pk episode_id=episode.pk %}">< Score</a>
		</div>
	</div>

	<div class="row">
		<div class="col">
			<h3>{{drag_race.display_name}}</h3>
		</div>
	</div>

	<div class="row">
		<div class="col">
			{% verbatim %}
			<h1 ng-show="!editTitle">Episode #{{episode.number}}<span ng-if="episode.title">: {{episode.title}}</span> Wildcards</h1>
			{% endverbatim %}
		</div>
	</div>

	{% if participant.site_admin %}
		<div class="row">
			<div class="col">
				{% verbatim %}
				<label for="queen">Queen:</label>
				<select 
					id="id_queen" 
					name="queen" 
					class="form-control"
					ng-change="updateCurrentQueen()"
					ng-model="queenSelector">>
					<option ng-model="currentQueen" ng-repeat="queen in allQueens track by $index" value="{{$index}}">{{queen.name}}</option>
				</select>
				<label for="rule">Appearance Type:</label>
				<select 
					id="id_appearance" 
					name="appearance" 
					class="form-control"
					ng-change="updateCurrentType()"
					ng-model="typeSelector">
					<option 
					ng-model="currentType" ng-repeat="type in appearanceTypes track by $index" value="{{$index}}">({{type.point_value}} pts) {{type.name}}</option>
				</select>
				
				<div class="spacer-medium"></div>
				<input ng-if="currentQueen && currentType" type="submit" value="add appearance" class="form-control btn btn-primary" name="addscore" id="id_addscore" ng-click="addAppearance(currentRule, currentQueen)"/>
				{% endverbatim %}
			</div>
		</div>
	{% endif %}
	<div class="row">
		<div class="col">
			<table class="table">
				<tr>
					<th>Queen</th><th>Appearance Type</th><th>Points</th><td></td>
				</tr>
				<tr ng-repeat="appearance in appearances">
					{% verbatim %}
					<th>{{appearance.queen.name}}</th>
					<td>
						<p>{{appearance.appearance.name}}</p>
						<p class="text-secondary">{{appearance.appearance.description}}</p>
					</td>
					<td>{{appearance.appearance.point_value}}</td>

					{% endverbatim %}
					<td>
						{% if participant.site_admin %}

							{% verbatim %}
								<input type="submit" class="btn btn-sm btn-danger" value="remove" name="deletescore" id="id_deleteappearance_{{appearance.pk}}"
								ng-click="deleteAppearance(appearance)">
							{% endverbatim %}
						{% endif %}
					</td>
				</tr>
			</table>
		</div>
	</div>
</span>
{% endblock %}

templates/pages/setepisodescores.html
{% extends 'base.html' %}
{% load static helper_tags %}
{% block page_title %} | Score Episode{% endblock %}
{% block extra_scripts %}
	<script type="text/javascript" src="{% static 'angular/episodescore.js' %}"></script>
{% endblock %}

{% block page_content %}
<input type="hidden" id="id_episodeId" value="{{episode.pk}}" />

<div class="row">
	<div class="col-sm-4 col-md-9">
		<h3><a href="{% url 'dragrace_stats' dragrace_id=drag_race.pk %}">{{drag_race.display_name}}</a></h3>
	</div>
	<div class="col-1">
		<a href="{% url 'set_episode_wildcards' dragrace_id=drag_race.pk episode_id=episode.pk%}" class="marker">Wildcards</a>
	</div>
</div>

<div class="row">
	<div class="col-sm-12 col-md-8">
		<h1 ng-show="!editTitle">
			<a href="{% url 'episode_detail' episode_id=episode.pk %}">
		{% verbatim %}Episode #{{episode.number}}<span ng-if="episode.title">: {{episode.title}}{% endverbatim %}</span></a></h1>
		

		{% if participant.site_admin %}
		{% verbatim %}
			<input ng-show="editTitle" type="text" class="form-control" ng-model="episode.title" />
		{% endverbatim %}
		{% endif %}
	</div>
	{% if participant.site_admin %}
	<div class="col">
		<button class="btn btn-danger btn-sm" 
			ng-click="editTitle=true"
			ng-show="!editTitle">[E]</button>
		<button class="btn btn-primary btn-sm" 
			ng-click="editTitle=false; patchEpisode({'title': episode.title})"
			ng-show="editTitle"
			>[S]</button>
	</div>
	{% endif %}
</div>

{% if participant.site_admin %}
	<div class="row">
		<div class="col" ng-if="episode.is_scored">
			<input type="submit" id="id_unsetscored" name="unsetscored" value="Unset episode as scored" class="form-control btn btn-warning" ng-click="patchEpisode({'is_scored': false})"/>
		</div>
		<div class="col" ng-if="!episode.is_scored">
			<input type="submit" id="id_setscored" name="setscored" value="Set episode as scored" class="form-control btn btn-info" ng-click="patchEpisode({'is_scored': true})"/>

		</div>
		<div class="col" ng-if="episode.has_aired">
			<input type="submit" id="id_unsetscored" name="unsetscored" value="Unset episode as aired" class="form-control btn btn-warning" ng-click="patchEpisode({'has_aired': false})"/>

		</div>
		<div class="col" ng-if="!episode.has_aired">
			<input type="submit" id="id_setscored" name="setscored" value="Set episode as aired" class="form-control btn btn-info" ng-click="patchEpisode({'has_aired': true})"/>
		</div>
		<div class="col" ng-if="episode.is_scored">
			<input type="submit" id="id_resetstats" name="resetstats" value="Reset Stats" class="form-control btn btn-primary" ng-click="resetStats()"/>
		</div>
	</div>
	<div class="row">
		<div class="col">
			{% csrf_token %}
			{% verbatim %}
			<label for="rule">Rule:</label>
			<select 
				id="id_rule" 
				name="rule" 
				class="form-control"
				ng-change="updateCurrentRule()"
				ng-model="ruleSelector">
				<option 
				ng-model="currentRule" ng-repeat="rule in rules track by $index" value="{{$index}}">({{rule.point_value}} pts) {{rule.name}}</option>
			</select>
			<label for="queen">Queen:</label>
			<select 
				id="id_queen" 
				name="queen" 
				class="form-control"
				ng-change="updateCurrentQueen()"
				ng-model="queenSelector">>
				<option ng-model="currentQueen" ng-repeat="queen in queens track by $index" value="{{$index}}">{{queen.name}}</option>
			</select>
			<div class="spacer-medium"></div>
			<input ng-if="currentQueen && currentRule" type="submit" value="add score" class="form-control btn btn-primary" name="addscore" id="id_addscore" ng-click="addScore(currentRule, currentQueen)"/>
			{% endverbatim %}
		</div>
	</div>
{% endif %}
<div class="row">
	<div class="col">
		<table class="table">
			<tr>
				<th>Queen</th><th>Score</th><th>Points</th><td></td>
			</tr>
			<tr ng-repeat="score in scores">
				{% verbatim %}
				<th>{{score.queen.name}}</th>
				<td>
					<p>{{score.rule.name}}</p>
					<p class="text-secondary">{{score.rule.description}}</p>
				</td>
				<td>{{score.rule.point_value}}</td>

				{% endverbatim %}
				<td>
					{% if participant.site_admin %}

						{% verbatim %}
							<input type="submit" class="btn btn-sm btn-danger" value="remove" name="deletescore" id="id_deletescore_{{score.pk}}"
							ng-click="deleteScore(score)">
						{% endverbatim %}
					{% endif %}
				</td>
			</tr>
		</table>
	</div>
</div>
{% endblock %}

templates/pages/wildcardlist.html
{% extends 'base.html' %}
{% load helper_tags %}
{% block page_title %} | Wildcards {% endblock %}
{% block page_content %}
	<div class="row">
		<div class="col">
			<h1>Wildcard Queens</h1>
		</div>
	</div>
	{% for participant in panel.participants.all %}
		<div class="row">
			<div class="col-2">
				<h3>{{participant.name}}</h3>
			</div>
			<div class="row">
				<div class="col">
					<h4>Queens</h4>
				{% with participant|wildcard_queens:panel as wildqueens %}
					<ul>
						{% for wildqueen in wildqueens %}
							<li>{{wildqueen.queen.name}}</li>
						{% endfor %}
					</ul>
				{% endwith %}
				</div>
			</div>
			{% if is_captain %}
			{% with participant|available_wildcard_queens:panel as availablequeens %}
			<div class="col">
				<form method="POST" action="">
					{% csrf_token %}
					<input type="hidden" id="id_participant" name="participant" value="{{participant.pk}}" />
					<select name="wildcard_queen" id="id_wildcard_queen" class="form-control">
						<option></option>
						{% for queen in availablequeens %}
							<option value="{{queen.pk}}">{{queen.name}}</option>
						{% endfor %}
					</select>
					<input type="submit" id="id_addwildqueen" name="addwildqueen" value="Add to Wildcard Queen List" class="form-control btn btn-primary"/>
				</form>
			</div>
			{% endwith %}
			{% endif %}
		</div>

		<hr />
	{% endfor %}
{% endblock %}